"""76 Standard Solutions for TRIZ Su-Field modeling."""
from __future__ import annotations

from src.triz.models import StandardSolution

STANDARD_SOLUTIONS: dict[int, StandardSolution] = {
    # === Class 1: Methods of building and destroying Su-Field models (13) ===
    1: StandardSolution(1, "1", "Synthesize complete Su-Field",
        "If a Su-Field is incomplete (only S1+S2 or S1+F), introduce the missing element.",
        "Incomplete Su-Field exists"),
    2: StandardSolution(2, "1", "Introduce S3 to eliminate harmful interaction",
        "Add a third substance S3 between S1 and S2 to block harmful effects.",
        "Harmful interaction exists between S1 and S2"),
    3: StandardSolution(3, "1", "Transition to complex Su-Field",
        "Increase complexity by introducing a second field or extending the existing field chain.",
        "Simple Su-Field lacks desired effect"),
    4: StandardSolution(4, "1", "Transition to Su-Field with modified S1 or S2",
        "Modify S1 or S2 to improve control over the interaction field.",
        "Interaction needs finer control"),
    5: StandardSolution(5, "1", "Transition to Su-Field with field modulation",
        "Use field modulation (pulse, variable frequency) instead of static field.",
        "Static field insufficient for desired effect"),
    6: StandardSolution(6, "1", "Transition to Su-Field by introducing field in environment",
        "Use a field naturally present in the environment as the interaction medium.",
        "Environment provides available field resource"),
    7: StandardSolution(7, "1", "Use natural phenomena as fields",
        "Exploit gravity, thermal expansion, capillary action, or other natural effects as fields.",
        "Need a field without introducing new equipment"),
    8: StandardSolution(8, "1", "Synthesize ferromagnetic Su-Field",
        "Use magnetic field and ferromagnetic substances to build a controlled Su-Field.",
        "Need precise remote control of substances"),
    9: StandardSolution(9, "1", "Use ferromagnetic additives in S1 or S2",
        "Add ferromagnetic particles to a substance to enable magnetic field control.",
        "Non-magnetic substance needs field-based control"),
    10: StandardSolution(10, "1", "Use ferromagnetic S3 to control harmful interactions",
        "Introduce ferromagnetic third substance that responds to magnetic field for separation.",
        "Need to separate or control harmful interaction"),
    11: StandardSolution(11, "1", "Use environment as a source of S3",
        "Use air, water, or other environmental substances as the third substance S3.",
        "Environment contains suitable material for S3"),
    12: StandardSolution(12, "1", "Use modified environment as S3",
        "Modify the environment (heat, ionize, etc.) to serve as an effective S3.",
        "Raw environment insufficient; modification needed"),
    13: StandardSolution(13, "1", "Use environment modifications with field effects",
        "Combine environmental substance modifications with a field for complete Su-Field.",
        "Need combined substance-and-field approach"),

    # === Class 2: Evolution of Su-Field models (23) ===
    14: StandardSolution(14, "2", "Transition to bi-system or poly-system",
        "Combine two or more identical or similar Su-Field systems into a unified system.",
        "Single system reaches its performance limit"),
    15: StandardSolution(15, "2", "Increase degree of fragmentation",
        "Move from solid to powder, paste, liquid, gas, plasma, or field.",
        "Need finer granularity of substance"),
    16: StandardSolution(16, "2", "Transition to capillary-porous substance",
        "Use capillary-porous materials within the Su-Field for enhanced interaction.",
        "Need increased surface area or fluid transport"),
    17: StandardSolution(17, "2", "Increase dynamism of system",
        "Make the system more flexible, adaptable, or tunable.",
        "System is too rigid for changing conditions"),
    18: StandardSolution(18, "2", "Transition to micro-level",
        "Replace macro-level actions with micro-level (molecular, atomic, field) processes.",
        "Macro-level approach has reached physical limits"),
    19: StandardSolution(19, "2", "Use frequency matching and coordination",
        "Match natural frequencies of substances and fields for resonance effects.",
        "Need stronger interaction without more energy"),
    20: StandardSolution(20, "2", "Introduce feedback in Su-Field",
        "Use feedback between substances and fields for self-regulation.",
        "Need adaptive control of the interaction"),
    21: StandardSolution(21, "2", "Use pulsed or periodic fields",
        "Replace continuous fields with pulsed, periodic, or modulated fields.",
        "Continuous field causes unwanted side effects"),
    22: StandardSolution(22, "2", "Use traveling field waves",
        "Use standing or traveling waves as field carriers.",
        "Need to transport substances or energy contactlessly"),
    23: StandardSolution(23, "2", "Use biological or biochemical effects",
        "Incorporate biological materials or processes as the field or substance.",
        "Conventional fields cannot achieve the desired effect"),
    24: StandardSolution(24, "2", "Use specialized field types",
        "Select fields with specific penetration, control, or interaction characteristics.",
        "Generic field cannot meet specialized requirements"),
    25: StandardSolution(25, "2", "Use dual fields simultaneously",
        "Apply two different fields simultaneously to achieve a combined effect.",
        "Single field insufficient to produce required effect"),
    26: StandardSolution(26, "2", "Make fields self-regulating",
        "Design the field to automatically adjust based on system state.",
        "Need self-adapting field control"),
    27: StandardSolution(27, "2", "Introduce a substance that changes properties under field",
        "Use substances that change phase, shape, or behavior in response to specific fields.",
        "Need a field-responsive control element"),
    28: StandardSolution(28, "2", "Use fields that provide multiple effects",
        "Choose fields that simultaneously perform useful and control functions.",
        "Need to reduce component count in Su-Field"),
    29: StandardSolution(29, "2", "Use additives that improve field-to-substance coupling",
        "Introduce substances that enhance energy transfer from field to substance.",
        "Poor coupling between field and substance"),
    30: StandardSolution(30, "2", "Use substances with graded or variable properties",
        "Employ materials with gradient composition, porosity, or other varying properties.",
        "Uniform substance cannot meet conflicting requirements"),
    31: StandardSolution(31, "2", "Decompose object into independently mobile parts",
        "Break a rigid object into articulated or independently moving sections.",
        "Rigid structure limits adaptability"),
    32: StandardSolution(32, "2", "Use inverse functions for poly-systems",
        "Apply inverse or complementary functions within a poly-system.",
        "System needs opposing actions simultaneously"),
    33: StandardSolution(33, "2", "Transition from homogeneous to heterogeneous structures",
        "Move from uniform composition to layered, patterned, or composite structures.",
        "Homogeneous structure cannot meet conflicting requirements"),
    34: StandardSolution(34, "2", "Use holes and cavities in substances",
        "Introduce pores, channels, or cavities within solid substances.",
        "Need to reduce weight or enable fluid passage"),
    35: StandardSolution(35, "2", "Use flexible shells and thin films",
        "Replace bulk structures with membranes, films, or flexible shells.",
        "Need to reduce material use or add adaptivity"),
    36: StandardSolution(36, "2", "Use bubbles and foam structures",
        "Introduce gas bubbles or foam into liquid or solid substances.",
        "Need lightweight structure or enhanced surface interaction"),

    # === Class 3: Transition to supersystem and microsystem (6) ===
    37: StandardSolution(37, "3", "Transition to bi-system and poly-system at system level",
        "Combine multiple systems to form a supersystem with enhanced capabilities.",
        "Single system performance is insufficient"),
    38: StandardSolution(38, "3", "Develop bi-systems by merging complementary systems",
        "Merge systems with complementary functions to create a new, more capable bi-system.",
        "Need combined functionality beyond any single system"),
    39: StandardSolution(39, "3", "Transition to micro-level processing",
        "Move system operation from macro-level to molecular, atomic, or field-level processes.",
        "System has reached macro-level performance limits"),
    40: StandardSolution(40, "3", "Use specialized fields for micro-level control",
        "Employ fields that operate at micro-level (electric, magnetic, thermal gradients) for precise control.",
        "Mechanical control insufficient at micro-scale"),
    41: StandardSolution(41, "3", "Use self-assembly and self-organization",
        "Design components to self-assemble or self-organize into the desired system.",
        "Assembly complexity limits system scale"),
    42: StandardSolution(42, "3", "Use phase transitions at micro-level",
        "Exploit phase changes (melting, evaporation, crystallization) at micro-scale.",
        "Need energy storage or release at micro-level"),

    # === Class 4: Measurement and detection (17) ===
    43: StandardSolution(43, "4", "Use a Su-Field for detection instead of measurement",
        "If direct measurement is impossible, detect the field change caused by the substance.",
        "Direct measurement not feasible"),
    44: StandardSolution(44, "4", "Introduce a measurable additive",
        "Add a detectable substance (tracer, dye, isotope) to the object being measured.",
        "Object itself is not measurable"),
    45: StandardSolution(45, "4", "Use a synthetic field proxy",
        "Create an artificial field whose characteristics correlate with the measurement target.",
        "No direct field correlates with the property"),
    46: StandardSolution(46, "4", "Use resonance phenomena for detection",
        "Measure changes in resonant frequency, amplitude, or phase caused by the target.",
        "Need high-sensitivity detection"),
    47: StandardSolution(47, "4", "Use natural phenomena as sensors",
        "Exploit known physical or chemical effects (piezoelectric, thermoelectric, etc.) as sensors.",
        "Need low-cost or passive detection"),
    48: StandardSolution(48, "4", "Measure by transforming the field type",
        "Convert the detection field to a different, easier-to-measure field type.",
        "Original detection field hard to measure directly"),
    49: StandardSolution(49, "4", "Use ferromagnetic substances for magnetic detection",
        "Apply magnetic field to detect ferromagnetic tracers or markers.",
        "Need remote detection capability"),
    50: StandardSolution(50, "4", "Use biological detection systems",
        "Leverage biological sensitivity (e.g., smell, taste, immune response) for detection.",
        "Technical sensors insufficiently sensitive"),
    51: StandardSolution(51, "4", "Use copies or models instead of original",
        "Detect the state of a simplified model or copy instead of the actual object.",
        "Object is too large, dangerous, or inaccessible"),
    52: StandardSolution(52, "4", "Measures by observing field state changes",
        "Observe how the detection field changes after interacting with the object.",
        "Need non-contact measurement"),
    53: StandardSolution(53, "4", "Use gradient fields for spatial measurement",
        "Create a known field gradient and measure position from the field value.",
        "Need to measure position or distribution"),
    54: StandardSolution(54, "4", "Use time-domain measurements",
        "Measure the time delay, phase shift, or frequency change of a field passing through the system.",
        "Spatial measurement not practical"),
    55: StandardSolution(55, "4", "Use the environment as a source for the sensing field",
        "Exploit naturally occurring fields (ambient light, thermal radiation) as detection carriers.",
        "Need passive, non-invasive detection"),
    56: StandardSolution(56, "4", "Use noise or interference as detection signal",
        "Analyze noise, scatter, or interference patterns as measurement signals.",
        "Direct signal is masked by noise"),
    57: StandardSolution(57, "4", "Use differential measurement techniques",
        "Compare two measurements under different conditions to isolate the target property.",
        "Environmental variations mask the measurement"),
    58: StandardSolution(58, "4", "Use feedback control in measurement systems",
        "Employ active feedback to lock onto and track the measured parameter.",
        "Passive measurement drifts or lacks sensitivity"),
    59: StandardSolution(59, "4", "Convert qualitative to quantitative measurements",
        "Use threshold detectors, arrays, or multiple discrete sensors to quantify qualitative properties.",
        "Only qualitative observation is possible"),

    # === Class 5: Strategies for simplification and improvement (17) ===
    60: StandardSolution(60, "5", "Introduce substances that are easily removable",
        "Use temporary substances (sacrificial coatings, soluble cores) that are removed later.",
        "Need temporary function without permanent modification"),
    61: StandardSolution(61, "5", "Use foams, aerogels, and lightweight structures",
        "Replace solid substances with porous or foam structures to reduce weight and material.",
        "Need lighter or more porous substances"),
    62: StandardSolution(62, "5", "Use fields to replace mechanical connections",
        "Replace physical contact with field-based interaction (magnetic levitation, etc.).",
        "Mechanical contact causes wear or contamination"),
    63: StandardSolution(63, "5", "Use self-regulating field sources",
        "Design fields that automatically adjust intensity based on the system's needs.",
        "Need automatic field control without external controller"),
    64: StandardSolution(64, "5", "Use available fields in the environment",
        "Leverage existing environmental fields (solar, thermal, gravitational) rather than introducing new ones.",
        "Need to minimize new field sources"),
    65: StandardSolution(65, "5", "Use virtual substances (shadows, images, holograms)",
        "Replace physical substances with optical or virtual representations.",
        "Physical substance too expensive or impractical"),
    66: StandardSolution(66, "5", "Replace object with its copy or model",
        "Work with a model, simulation, or digital twin instead of the real system.",
        "Real system is too costly or dangerous to experiment with"),
    67: StandardSolution(67, "5", "Use disposable or consumable substances",
        "Design parts that are consumed during normal operation and easily replaced.",
        "Wear and maintenance is unavoidable"),
    68: StandardSolution(68, "5", "Use the object itself as a tool",
        "Make the object perform its own processing or handling (self-service).",
        "Need to simplify the system by eliminating tooling"),
    69: StandardSolution(69, "5", "Introduce substances that change the environment locally",
        "Modify the immediate environment around a component rather than the entire environment.",
        "Cannot modify the overall environment"),
    70: StandardSolution(70, "5", "Use multiple functions of a single substance",
        "Design a substance to serve multiple functions simultaneously.",
        "Too many separate components in the system"),
    71: StandardSolution(71, "5", "Use additive manufacturing principles",
        "Build up structures incrementally using deposited layers of material.",
        "Subtractive manufacturing wastes too much material"),
    72: StandardSolution(72, "5", "Use substances with memory effects",
        "Employ shape-memory alloys, smart materials, or hysteresis effects as functional elements.",
        "Need passive actuation based on environment"),
    73: StandardSolution(73, "5", "Use micro-encapsulation and controlled release",
        "Encapsulate active substances in micro-containers for timed or triggered release.",
        "Substance degrades or reacts before reaching target"),
    74: StandardSolution(74, "5", "Use inverse phase transitions",
        "Exploit phase transitions in the reverse direction (e.g., solidification for joining).",
        "Standard techniques insufficient for joining/separation"),
    75: StandardSolution(75, "5", "Combine opposite properties in a structured arrangement",
        "Layer materials with opposite properties to achieve combined performance.",
        "Single material cannot satisfy conflicting requirements"),
    76: StandardSolution(76, "5", "Use self-similar and multi-scale structures",
        "Design structures that repeat at different scales (fractal, hierarchical patterns).",
        "Need consistent properties across scales"),
}
